### PR TITLE
docs: fix example

### PR DESCRIPTION
**Pull request by brayniac**
* use expect() in the example instead of try
* mark example as no_run

### CODE REVIEW

**Comment by gz** [comment]
Thank you for fixing this, the build is passing now!

**Comment by brayniac** [comment]
@gz no problem! Might be worth doing a release to crates.io?

**Comment by gz** [comment]
Sure, I released 0.3.1 on crates.io.

**Comment by gz** [comment]
Sorry disregard that I should rather release a 0.4.1

**Comment by gz** [comment]
Done

**Pull request merged**
